instagram/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :models
  resources :instapics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "instapics#index"
end

instagram/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

instagram/app/models/instapic.rb
class Instapic < ApplicationRecord
  belongs_to :user
end

instagram/app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

instagram/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

instagram/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    before_action :authenticate_user!
end

instagram/app/controllers/instapics_controller.rb
class InstapicsController < ApplicationController
  before_action :set_instapic, only: [:show, :edit, :update, :destroy]

  # GET /instapics
  # GET /instapics.json
  def index
    @instapics = Instapic.all
  end

  # GET /instapics/1
  # GET /instapics/1.json
  def show
  end

  # GET /instapics/new
  def new
    @instapic = Instapic.new
  end

  # GET /instapics/1/edit
  def edit
  end

  # POST /instapics
  # POST /instapics.json
  def create
    @instapic = Instapic.new(instapic_params)
    @instapic.user = current_user

    respond_to do |format|
      if @instapic.save
        format.html { redirect_to @instapic, notice: 'Instapic was successfully created.' }
        format.json { render :show, status: :created, location: @instapic }
      else
        format.html { render :new }
        format.json { render json: @instapic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instapics/1
  # PATCH/PUT /instapics/1.json
  def update
    respond_to do |format|
      if @instapic.update(instapic_params)
        format.html { redirect_to @instapic, notice: 'Instapic was successfully updated.' }
        format.json { render :show, status: :ok, location: @instapic }
      else
        format.html { render :edit }
        format.json { render json: @instapic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instapics/1
  # DELETE /instapics/1.json
  def destroy
    @instapic.destroy
    respond_to do |format|
      format.html { redirect_to instapics_url, notice: 'Instapic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instapic
      @instapic = Instapic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instapic_params
      params.require(:instapic).permit(:picture, :post, :user_id)
    end
end

instagram/app/helpers/application_helper.rb
module ApplicationHelper
end

instagram/app/helpers/instapics_helper.rb
module InstapicsHelper
end

instagram/app/views/instapics/_form.html.erb
<%= form_with(model: instapic, local: true) do |form| %>
  <% if instapic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instapic.errors.count, "error") %> prohibited this instapic from being saved:</h2>

      <ul>
      <% instapic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture, id: :instapic_picture %>
  </div>

  <div class="field">
    <%= form.label :caption %>
    <%= form.text_field :caption, id: :instapic_post %>
  </div>

  <!-- <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :instapic_user_id %>
  </div> -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

instagram/app/views/instapics/edit.html.erb
<h1>Editing Instapic</h1>

<%= render 'form', instapic: @instapic %>

<%= link_to 'Show', @instapic %> |
<%= link_to 'Back', instapics_path %>

instagram/app/views/instapics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Instapics</h1>

<table>
  <thead>
    <tr>
      <th>Picture</th>
      <th>Caption</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instapics.each do |instapic| %>
      <tr>
        <td><%= instapic.picture %></td>
        <td><%= instapic.caption %></td>
        <td><%= instapic.user %></td>
        <td><%= link_to 'Show', instapic %></td>
        <td><%= link_to 'Edit', edit_instapic_path(instapic) %></td>
        <td><%= link_to 'Destroy', instapic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instapic', new_instapic_path %>

instagram/app/views/instapics/new.html.erb
<h1>New Instapic</h1>

<%= render 'form', instapic: @instapic %>

<%= link_to 'Back', instapics_path %>

instagram/app/views/instapics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Picture:</strong>
  <%= @instapic.picture %>
</p>

<p>
  <strong>Caption:</strong>
  <%= @instapic.caption %>
</p>

<p>
  <strong>User:</strong>
  <%= @instapic.user %>
</p>

<%= link_to 'Edit', edit_instapic_path(@instapic) %> |
<%= link_to 'Back', instapics_path %>

instagram/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <p> Logged in as: <%= current_user.email %></p>
      <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
    <% else %>
      <p>You are not logged in!</p>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

  </body>
</html>

instagram/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>